favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://drupal.dev/themes/bootstrap/favicon.ico'
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: false
schemas:
  bootstrap: 8000
  dmcn: 8000
